// Generated by scripts/build-doc-index.mjs. Do not edit.
export const chapters = [
  {
    "id": "overview",
    "label": "系统职责",
    "order": 1,
    "estimate": "2 分钟",
    "keywords": [
      "系统概览",
      "注册",
      "OAuth",
      "号池",
      "联邦"
    ],
    "path": "docs/manual/chapters/01-overview.md",
    "content": "## 它是什么\n\ntouch-squirrel 是把“注册、拿到凭证、存进号池”这几件事放在一起做的宿主。它不替代邮箱、代理或浏览器；它负责让这些外部能力按同一条流程工作，并保留每一步的状态和产物。\n\n## 最简单的理解\n\n把它当成一个仓库管理员：邮箱负责收验证码，代理负责出门，浏览器负责过验证，OAuth 负责换钥匙。touch-squirrel 只负责安排顺序、记录结果，以及在某一步失败时告诉你失败在哪里。\n\n- 注册任务负责创建账号和 SSO 会话\n- OAuth 负责把会话换成可用凭证\n- 号池负责保存、巡检和补充凭证\n- 联邦负责让多台机器按需要分担任务",
    "story": "## 阅读故事\n\n想象你要整理一批新钥匙。有人去前台领号，有人收短信验证码，有人开门验证钥匙是否能用。没有管理员时，钥匙、纸条和失败记录会散在各处；有了 touch-squirrel，每把钥匙都会有来源、状态和最终去向。"
  },
  {
    "id": "prerequisites",
    "label": "运行准备",
    "order": 2,
    "estimate": "2 分钟",
    "keywords": [
      "运行准备",
      "邮箱",
      "代理",
      "clearance",
      "Turnstile"
    ],
    "path": "docs/manual/chapters/02-prerequisites.md",
    "content": "## 运行前要准备什么\n\n先准备一个独立运行根目录。这里保存配置、日志、运行状态、PID/锁文件、每次任务的输出和本地凭证池。两台机器不要共用同一个本地根目录。\n\n## 三个外部条件\n\n- **邮箱**：能创建地址并读取验证码即可。供应商不同，流程不变。\n- **代理与 clearance**：注册请求和 clearance 必须走同一出口。换代理时，二者要一起换，否则 cookie 可能失效。\n- **浏览器打码**：browser provider 通过 `GROK_PYTHON` 调用 Python 与 Playwright；lite provider 调用轻量服务。浏览器模式通常决定整体速度。",
    "story": "## 阅读故事\n\n注册好比进一座需要邀请函的楼：邮箱是信箱，代理是出行路线，clearance 是门卫见过你后发的通行贴纸。你不能从 A 路线拿贴纸，再从 B 路线进门。"
  },
  {
    "id": "related-projects",
    "label": "关联项目",
    "order": 3,
    "estimate": "2 分钟",
    "keywords": [
      "touch-mail-router",
      "Resin",
      "邮箱接收",
      "代理池"
    ],
    "path": "docs/manual/chapters/03-related-projects.md",
    "content": "## touch-mail-router\n\n[touch-mail-router](https://github.com/TalexDreamSoul/touch-mail-router) 可以作为邮箱接收层。它提供兼容 DuckMail 的账户、令牌和收件箱 API，也能通过 Cloudflare Email Worker、转发、DoneMail 或入站 API 接收验证码邮件。\n\n对注册流水线来说，它只需要做到两件事：创建邮箱，读取验证码。其余邮件接入细节留在 mail router 内部。\n\n## Resin\n\n[Resin](https://github.com/Resinat/Resin) 可以作为代理池和稳定出口。把 Resin 的 HTTP forward proxy 同时配置给 `REGISTER_PROXY` 与 `CLEARANCE_PROXY`，可以让注册与 clearance 保持同一出口。\n\n当前流水线尚未消费每账号 Resin sticky 配置。需要固定出口时，先使用统一入口；账号级 sticky 必须等真正注入请求链路后再启用。",
    "story": "## 阅读故事\n\nmail router 像收发室，把所有验证码信件送到同一个可查询的信箱；Resin 像调度中心，为每次出门选择稳定路线。一个解决“信到了没有”，一个解决“从哪里出去”。"
  },
  {
    "id": "worker",
    "label": "任务启动",
    "order": 4,
    "estimate": "1 分钟",
    "keywords": [
      "worker",
      "run",
      "PID",
      "任务启动"
    ],
    "path": "docs/manual/chapters/04-worker.md",
    "content": "## 前台命令不直接注册\n\n启动 `xai-accounts` 后，前台命令先创建本次 run 的状态：目标数、日志路径和输出目录。随后它以同一可执行文件重新拉起独立的 `--worker` 子进程，真正执行注册。\n\n## 为什么要分开\n\n前台负责启动、停止和查看状态；worker 负责耗时工作。PID 文件和独占锁保证同一个根目录同一时间只有一个注册 worker。\n\n停止时，worker 会先停止生产新任务，再让已经在 OAuth 队列里的工作收尾，避免账号刚注册成功就被无序切断。",
    "story": "## 阅读故事\n\n前台像值班台，只负责开工、叫停和报进度；worker 像进入仓库干活的班组。值班台下班不代表班组立刻把手里的箱子扔掉。"
  },
  {
    "id": "pipeline",
    "label": "四段流水线",
    "order": 5,
    "estimate": "3 分钟",
    "keywords": [
      "Solve",
      "Prepare",
      "Confirm",
      "OAuth",
      "队列"
    ],
    "path": "docs/manual/chapters/05-pipeline.md",
    "content": "## S：Solve\n\n获取 Turnstile token，并放入短生命周期的 T 队列。浏览器模式通常串行打码，目的是减少多浏览器争抢资源和出口不稳定。\n\n## P：Prepare\n\n创建邮箱、申请并轮询验证码，再把邮箱、密码和验证码放进 Q 队列。队列只保留少量就绪项，避免为了小目标过量创建邮箱。\n\n## C：Confirm 与 OAuth\n\nC 会原子地领取一对 T+Q，提交注册并提取 SSO。成功后立即写入账号与会话文件，再交给 OAuth 交换、探活和 CPA JSON 落盘。\n\n- S、P、C 是同一 worker 内的 Go goroutine，不是四个系统进程\n- T/Q 是有容量和过期时间的内存库存\n- Python 或 Node 只在需要 bridge 时跨进程参与",
    "story": "## 阅读故事\n\n这像装配线：先准备通行码，再准备身份资料，然后把两样东西一起交到窗口办理。办理成功后，另一条线去验钥匙、编号、入库。"
  },
  {
    "id": "concurrency",
    "label": "并发控制",
    "order": 6,
    "estimate": "2 分钟",
    "keywords": [
      "并发",
      "限流",
      "邮箱",
      "浏览器",
      "OAuth"
    ],
    "path": "docs/manual/chapters/06-concurrency.md",
    "content": "## 速度不是越高越好\n\n并发的目标是稳定完成，不是把 CPU 跑满。浏览器 provider 会把 Solve 限制为单个物理并发；这通常是整条流水线的自然上限。\n\n## 各段的默认约束\n\n- P worker 最多 4 个，待收码邮箱也有限制\n- C 默认 2 个，避免注册端和邮箱端同时被压垮\n- OAuth 默认 2 个，并按 `OAUTH_MIN_INTERVAL_SEC` 限速\n\n吞吐变慢时，先判断瓶颈在打码、邮箱还是服务端限流。盲目增加 P/C worker 往往只会积压更多半成品。",
    "story": "## 阅读故事\n\n一家餐馆只有一个出菜口时，多请十个点餐员不会让菜更快端上来；先找到出菜口，才知道该加厨师、加服务员，还是换供应。"
  },
  {
    "id": "federation",
    "label": "联邦派发",
    "order": 7,
    "estimate": "2 分钟",
    "keywords": [
      "联邦",
      "heartbeat",
      "assignment",
      "主节点",
      "从节点"
    ],
    "path": "docs/manual/chapters/07-federation.md",
    "content": "## 主节点只派需求，不派秘密\n\n主节点维护健康凭证数量和目标数量，计算 `need = target − healthy`。它不会把账号、邮箱或 token 下发给从节点。\n\n## 从节点怎么领取工作\n\n从节点定期发送 heartbeat，报告自身容量、是否忙碌和当前目标。主节点只有在仍有缺口且从节点不忙时，才回复 assignment。\n\n一次 assignment 会同时受到全局缺口、`CLUSTER_ASSIGN_MIN`、`CLUSTER_ASSIGN_MAX` 与从节点 capacity 限制，最终通常是 0 或 1–10。多主场景下，从节点选择最大的 assignment 执行。\n\n完成后，从节点可上传凭证，并向主节点报告完成数、上传数和失败数。",
    "story": "## 阅读故事\n\n主节点像库房管理员，只说“还缺 8 箱”；从节点各自去本地采购和验货，完成后只报“交了几箱、坏了几箱”。货源和工具仍留在各自手里。"
  },
  {
    "id": "plugins",
    "label": "多语言与插件",
    "order": 8,
    "estimate": "3 分钟",
    "keywords": [
      "插件",
      "Go",
      "Python",
      "Node",
      "bridge",
      "NDJSON"
    ],
    "path": "docs/manual/chapters/08-plugins.md",
    "content": "## Go 原生与 hybrid\n\n当前 xAI 主线的协议、队列、OAuth 与 CPA 写入都在 Go 流水线中。它标记为 hybrid，是因为 Go 编排时会调用 Python 浏览器脚本完成 Turnstile mint。\n\n## Bridge\n\nbridge 插件由 Host 启动外部 Python 或 Node 进程。Host 传入 target、输出目录和插件配置；子进程通过 stdout 输出 NDJSON，回传 progress、log、captcha、artifact、error、done。\n\n## JS runtime 的当前边界\n\nmanifest 可以声明 `go`、`js`、`hybrid` 或 bridge。当前通用 runner 已支持 xAI 的 Go 流水线和 bridge；纯 JS registrar 的通用执行器尚未落地，不能只因 manifest 写了 JS 就认为它已可运行。",
    "story": "## 阅读故事\n\nGo 像总导演，Python 或 Node 像受邀的专业演员。演员可以完成自己的镜头，但场记、进度、产物和收工规则都必须回到导演手里。"
  },
  {
    "id": "storage",
    "label": "凭证与分享",
    "order": 9,
    "estimate": "2 分钟",
    "keywords": [
      "CPA",
      "凭证",
      "号池",
      "配置分享",
      "巡检"
    ],
    "path": "docs/manual/chapters/09-storage.md",
    "content": "## 每次任务都有独立产物\n\n每个 run 分目录保存 SSO、会话、CPA 与 discarded。成功 CPA 是独立 JSON 文档；本地池用于节点内管理，CPA Management 可用于远端存储和分发。\n\n## 巡检与补号\n\n巡检要区分暂时限流、凭证失效和额度耗尽。补号是独立动作，不应和清理绑定在一起，否则一次误判会同时丢失凭证和补充能力。\n\n## 配置分享的边界\n\n配置链接只分享邮箱、TouchMail、代理和 clearance 等非敏感字段，并以非空合并导入。CPA 密钥、集群密钥、状态页密码和本机路径不在共享范围内。",
    "story": "## 阅读故事\n\n凭证像仓库里的封条：每一批货都要有自己的箱号和入库单。共享的是收货流程，不是仓库钥匙和保险柜密码。"
  },
  {
    "id": "troubleshooting",
    "label": "排障顺序",
    "order": 10,
    "estimate": "2 分钟",
    "keywords": [
      "排障",
      "日志",
      "吞吐",
      "联邦",
      "worker"
    ],
    "path": "docs/manual/chapters/10-troubleshooting.md",
    "content": "## 任务不动\n\n先看当前阶段、worker PID 和 run 日志。配置抓取失败、邮箱收码超时、打码失败和 OAuth 失败是四类不同问题，不能统一叫“注册失败”。\n\n## 吞吐过低\n\n浏览器打码为串行时，S 就是上限。先测 token mint 耗时、代理质量和邮箱延迟，再考虑切换 solver 或调整并发。\n\n## 联邦没有分配\n\n确认从节点 role、主地址、联邦 token 和 heartbeat；再确认主节点是否已经达到目标，或从节点是否报告 busy。没有 assignment 不一定代表连接失败，可能只是没有缺口。",
    "story": "## 阅读故事\n\n排障像查一条停住的传送带：先看电源和当前卡点，再看上一站有没有供料，最后才考虑加速。把所有故障都叫“机器坏了”，修不好任何一处。"
  }
] as const;
